### PR TITLE
+ Add safari support

### PR DESCRIPTION
**Pull request by AthanaseKa**

### CODE REVIEW

**Comment by ivantsov** [comment]
Hi @AthanaseKa, thanks for your PR. I'm gonna take a look at it asap, however at the moment I'm on vacation and can't guarantee that it'll be done any soon. Sorry for the delay...

**Comment by AthanaseKa** [comment]
Hi @ivantsov. No worries, I'm looking forward for your feedback !

**Comment by ivantsov** [comment]
Hi @AthanaseKa, finally I found time to review the PR.
So, I have a few questions/concerns about developing extensions for Safari:

- As far as I understood Safari doesn't support WebExtension API like Chrome, Opera and Firefox do. Am I right?
- As stated [here](https://developer.apple.com/library/content/documentation/NetworkingInternetWeb/Conceptual/SafariAppExtension_PG/CreatingandTestingYourFirstSafariAppExtension.html#//apple_ref/doc/uid/TP40017319-CH11-SW1) the only way to develop Safari extension is to use XCode and have Apple developer license. And as I see you updated the examples folder, so can you please explain how you managed to build the extension?

**Comment by AthanaseKa** [comment]
Hi @ivantsov, sorry for the delayed response I was on vacation.
To respond to your questions:
- Yes Safari doesn't support WebExtension API
- There are two types of "extensions" for safari, "extensions" and "plug-in's". I suggest you read [this](https://developer.apple.com/library/content/documentation/Tools/Conceptual/SafariExtensionGuide/Introduction/Introduction.html) short documentation to understand the differences between the two.

**Comment by tusbar** [comment]
This seems out of place for a project called `redux-webext`. :) Safari does not support WebExtensions.

**Comment by ivantsov** [comment]
Hey @tusbar, I thought about it as well and eventually decided to check how provided in the PR Safari's example works. However I still haven't managed to do that... If it works seamlessly than it might make sense to investigate.
Once I check the example I'll comment it here, unfortunately I'm a bit busy.

**Comment by ivantsov** [comment]
Hi @AthanaseKa, sorry for not getting back to you earlier...
I've investigated the link you sent and the PR as well. As far as I understood developing an extension for Safari has almost nothing similar to Chrome or Firefox. Moreover, it doesn't support WebExtension standard.
That's why I came to conclusion that I'm not able to provide users of `redux-webext` with a proper support for Safari. And because this very thing I don't want to include it into the package. Hope you understand my opinion. 
Nevertheless, I'd like to thank you once again for your interest in this particular project and in open-source as well. Hope you'll continue helping the community :)

**Comment by tusbar** [comment]
@AthanaseKa you should make another package, something like `redux-safari-extension`. :)

**Comment by AthanaseKa** [comment]
Hi @ivantsov @tusbar, thanks for the feedback !

I'll consider making another package, I'll keep you updated if I do so.

Thanks again !

**Pull request closed without merging**
